#   a116_buggy_image.py
import turtle as trtl
# formula
spider = trtl.Turtle()
legs = 16
incrament = 360 / legs

#add body
spider.goto(0,0)
spider.pensize(40)
spider.circle(20)

#add legs
spider.pensize(5)
spider.goto(0,20)
spider.setheading(incrament*8)
spider.circle(100, -90)
spider.penup()
spider.goto(0,20)
spider.pendown()
spider.setheading(incrament*9)
spider.circle(100, -90)
spider.penup()
spider.goto(0,20)
spider.pendown()
spider.setheading(incrament*10)
spider.circle(100, -90)
spider.penup()
spider.goto(0,20)
spider.pendown()
spider.setheading(incrament*11)
spider.circle(100, -90)
spider.penup()
spider.goto(0,20)
spider.pendown()
spider.setheading(incrament*5)
spider.circle(100, 90)
spider.penup()
spider.goto(0,20)
spider.pendown()
spider.setheading(incrament*6)
spider.circle(100, 90)
spider.penup()
spider.goto(0,20)
spider.pendown()
spider.setheading(incrament*7)
spider.circle(100, 90)
spider.penup()
spider.goto(0,20)
spider.pendown()
spider.setheading(incrament*8)
spider.circle(100, 90)
spider.penup()

#add head
spider.goto (0,-30)
spider.pendown()
spider.pensize(40)
spider.circle(5)
spider.penup()

#add eyes
spider.goto(10,-40)
spider.pencolor("purple")
spider.pensize(5)
spider.pendown()
spider.circle(5)
spider.penup()
spider.goto(-10,-40)
spider.pensize(5)
spider.pendown()
spider.circle(5)

spider.hideturtle()
wn = trtl.Screen()
wn.mainloop()
